<script setup lang="ts">
const pillars = [
  ['bi-briefcase-fill', 'Mayor Conectividad', 'Integración ágil con consolidadores globales, inventario aéreo y plataformas de emisión en tiempo real.'],
  ['bi-globe', 'Alianzas Estratégicas', 'Convenios mayoristas con operadores y cadenas hoteleras que garantizan mejores márgenes de comisión.'],
  ['bi-people-fill', 'Apoyo para tu Crecimiento', 'Capacitaciones continuas, soporte en cotizaciones complejas y mentoría de desarrollo de negocio.'],
  ['bi-send-fill', 'Más Oportunidades para Viajar', 'Tarifas preferenciales para tus clientes y acceso a viajes de familiarización para agentes.'],
]
const services = [
  ['bi-ticket-perforated-fill', 'Consolidación Aérea', 'Emisión inmediata y soporte en cambios, cancelaciones y reemisiones con las principales aerolíneas del mundo.', 'GDS & NDC Ready'],
  ['bi-building', 'Hotelería & Circuitos', 'Inventario directo en más de 300,000 hoteles globales y paquetes turísticos organizados con operadores de primer nivel.', 'Tarifas Netas B2B'],
  ['bi-shield-check', 'Asistencia al Viajero', 'Planes de cobertura médica internacional con comisiones preferenciales y emisión al instante para tus pasajeros.', 'Cobertura Global'],
  ['bi-mortarboard-fill', 'Academia CAVITUR', 'Formación integral para profesionales. Accede a certificaciones, webinars y herramientas digitales diseñadas para optimizar tus servicios.', 'Capacitación Continua'],
  ['bi-laptop', 'Herramientas Digitales', 'Acceso a cotizadores rápidos, plantillas de itinerarios y recursos de marketing listos para personalizar con tu marca.', 'Marketing Kit'],
  ['bi-headset', 'Soporte Estratégico B2B', 'Un equipo especializado que acompaña a nuestros aliados con atención personalizada, asesoría experta y soluciones estratégicas.', 'Atención Personalizada'],
]
</script>

<template>
  <section id="inicio" class="hero-section py-5 position-relative"><div class="container py-lg-5"><div class="row align-items-center gy-5"><div class="col-lg-6"><div class="d-inline-flex align-items-center gap-2 px-3 py-1 rounded-pill bg-cream border border-cavitur-green-subtle mb-3"><i class="bi bi-stars text-cavitur-orange"></i><span class="small fw-bold text-cavitur-green">PARA FREELANCE Y AGENCIAS DE VIAJES</span></div><h1 class="display-4 fw-extrabold text-dark-green mb-3">Impulsa tu negocio turístico con el respaldo de <span class="text-cavitur-orange fst-italic">CAVITUR</span></h1><p class="lead text-muted mb-4 fs-6"><strong>CAVITUR</strong> es el centro aliado estratégico que conecta a profesionales del turismo con mayor conectividad, tarifas mayoristas, soporte operativo y herramientas para escalar ventas.</p><div class="d-flex flex-wrap gap-3 mb-4"><a href="#contacto" class="btn btn-cavitur-green btn-lg px-4 py-3 rounded-pill fw-bold">Comenzar Alianza <i class="bi bi-arrow-right ms-2"></i></a><a href="#nosotros" class="btn btn-outline-cavitur-green btn-lg px-4 py-3 rounded-pill fw-bold">Conocer Más</a></div><div class="row g-3 pt-3 border-top"><div class="col-4"><h5 class="fw-bold text-cavitur-orange mb-0">+500</h5><small class="text-muted">Rutas & GDS</small></div><div class="col-4"><h5 class="fw-bold text-cavitur-orange mb-0">100%</h5><small class="text-muted">Apoyo B2B</small></div><div class="col-4"><h5 class="fw-bold text-cavitur-orange mb-0">24/7</h5><small class="text-muted">Acompañamiento</small></div></div></div><div class="col-lg-6"><div class="hero-banner-card p-4 rounded-4 shadow-lg position-relative text-white overflow-hidden"><div class="banner-overlay"></div><div class="position-relative z-1 p-md-3"><span class="badge bg-white text-dark-green fw-bold px-3 py-2 rounded-pill mb-3"><i class="bi bi-globe-americas me-1 text-cavitur-orange"></i> RED COLABORATIVA</span><h3 class="fw-bold mb-3">Conéctate. Colabora. Crece con CAVITUR.</h3><p class="text-white-50 small mb-4">Accede a la plataforma que centraliza negociaciones hoteleras, boletos aéreos, circuitos internacionales y capacitaciones de alto nivel.</p></div></div></div></div></div></section>
  <section id="pilares" class="py-5 bg-cavitur-dark-green text-white"><div class="container py-4"><div class="text-center max-w-700 mx-auto mb-5"><span class="text-cavitur-orange text-uppercase fw-bold letter-spacing-2 small">Ventajas Exclusivas</span><h2 class="display-6 fw-bold mt-2">¿Por qué unirte a la red CAVITUR?</h2><p class="text-white-50">Diseñado a la medida tanto para agencias consolidadas como para agentes independientes.</p></div><div class="row g-4"><div v-for="pillar in pillars" :key="pillar[1]" class="col-md-6 col-lg-3"><div class="pilar-card p-4 rounded-4 h-100 text-center"><div class="pilar-icon mx-auto mb-3"><i :class="['bi', pillar[0]]"></i></div><h5 class="fw-bold mb-2">{{ pillar[1] }}</h5><p class="text-white-50 small mb-0">{{ pillar[2] }}</p></div></div></div></div></section>
  <section id="servicios" class="py-5"><div class="container py-lg-4"><div class="text-center max-w-700 mx-auto mb-5"><span class="text-cavitur-orange text-uppercase fw-bold letter-spacing-2 small">Portafolio de Soluciones</span><h2 class="display-6 fw-bold text-dark-green mt-2">Herramientas que impulsan tus ventas</h2><p class="text-muted">Todo lo que necesitas para operar tu negocio de viajes con nivel mayorista.</p></div><div class="row g-4"><div v-for="service in services" :key="service[1]" class="col-md-6 col-lg-4"><div class="service-card p-4 rounded-4 border h-100"><div class="service-icon mb-3"><i :class="['bi', service[0]]"></i></div><h5 class="fw-bold text-dark-green mb-2">{{ service[1] }}</h5><p class="text-muted small mb-3">{{ service[2] }}</p><span class="badge bg-cream text-dark-green border fw-semibold">{{ service[3] }}</span></div></div></div></div></section>
</template>